apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: grafana-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
